# Generated by Django 5.0.3 on 2024-04-29 23:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='edificio',
            fields=[
                ('idEdificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEdificio', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='estadoPrestamo',
            fields=[
                ('idEstadoPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=45)),
                ('descripcionEstado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='implemento',
            fields=[
                ('idImplemento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreImplemento', models.CharField(max_length=45)),
                ('estadoImplemento', models.CharField(max_length=45)),
                ('edificioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='comentarioImplemento',
            fields=[
                ('idComentarioImplemento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('comentario', models.TextField()),
                ('implementoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.implemento')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('fechaHoraInicioPrestamo', models.DateTimeField()),
                ('fechaHoraFinPrestamo', models.DateTimeField()),
                ('comentario', models.TextField(null=True)),
                ('administradorBienestarNumeroDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradorBienestarNumeroDocumento', to=settings.AUTH_USER_MODEL)),
                ('estadoPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.estadoprestamo')),
                ('estudianteNumeroDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudianteNumeroDocumento', to=settings.AUTH_USER_MODEL)),
                ('idImplemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.implemento')),
            ],
        ),
    ]
