# Generated by Django 5.0.3 on 2024-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_estadoimplemento_remove_implemento_estadoimplemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaHoraFinPrestamo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaHoraInicioPrestamo',
            field=models.DateTimeField(null=True),
        ),
    ]
