# Generated by Django 5.0.3 on 2024-05-13 17:00

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_fechahorafinprestamo_and_more'),
        ('usuarios', '0002_razoncambio_usuario_lastlogin_historicalusuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaHoraFinPrestamo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaHoraInicioPrestamo',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Historicalimplemento',
            fields=[
                ('idImplemento', models.IntegerField(blank=True, db_index=True)),
                ('nombreImplemento', models.CharField(max_length=45)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('edificioId', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prestamos.edificio')),
                ('estadoImplementoId', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prestamos.estadoimplemento')),
                ('history_change_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical implemento',
                'verbose_name_plural': 'historical implementos',
                'db_table': 'trazabilidadImplemento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalprestamo',
            fields=[
                ('idPrestamo', models.IntegerField(blank=True, db_index=True)),
                ('fechaHoraCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('fechaHoraInicioPrestamo', models.DateTimeField()),
                ('fechaHoraFinPrestamo', models.DateTimeField()),
                ('comentario', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('administradorBienestarNumeroDocumento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estadoPrestamo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prestamos.estadoprestamo')),
                ('estudianteNumeroDocumento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_change_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idImplemento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prestamos.implemento')),
            ],
            options={
                'verbose_name': 'historical prestamo',
                'verbose_name_plural': 'historical prestamos',
                'db_table': 'trazabilidadPrestamo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
