# Generated by Django 5.0.3 on 2024-05-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_fechahorafinprestamo_and_more'),
        ('prestamos', '0003_historicalimplemento_historicalprestamo'),
    ]

    operations = [
    ]
