# Generated by Django 5.0.3 on 2024-05-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_merge_20240510_1634'),
        ('usuarios', '0003_razoncambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimplemento',
            name='history_change_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio'),
        ),
        migrations.AlterField(
            model_name='historicalprestamo',
            name='history_change_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaHoraFinPrestamo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaHoraInicioPrestamo',
            field=models.DateTimeField(),
        ),
    ]
