# Generated by Django 5.0.3 on 2024-05-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_alter_historicalimplemento_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalimplemento',
            table='trazabilidadImplemento',
        ),
        migrations.AlterModelTable(
            name='historicalprestamo',
            table='trazabilidadPrestamo',
        ),
    ]
