# Generated by Django 5.0.3 on 2024-05-22 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0004_alter_prestamo_fechahorafinprestamo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaEvento',
            fields=[
                ('idCategoriaEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoriaEvento', models.CharField(max_length=45)),
                ('descripcionCategoriaEvento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='estadoEvento',
            fields=[
                ('idEstadoEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstadoEvento', models.CharField(max_length=45)),
                ('descripcionEstadoEvento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraCreacion', models.DateField()),
                ('nombreEvento', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=255)),
                ('fechaHoraEvento', models.DateField()),
                ('lugar', models.CharField(max_length=255)),
                ('flyer', models.BinaryField()),
                ('descripcion', models.TextField()),
                ('aforo', models.SmallIntegerField()),
                ('asistentes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('categoriaEvento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.categoriaevento')),
                ('edificio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.edificio')),
                ('estadoEvento', models.ManyToManyField(to='eventos.estadoevento')),
                ('numeroDocumento_AdministradorBienestar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NumeroDocumentoadministradorBienestar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
