# Generated by Django 5.0.3 on 2024-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fechaHoraCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fechaHoraEvento',
            field=models.DateTimeField(),
        ),
    ]
