# Generated by Django 5.0.3 on 2024-06-02 00:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_fechahoracreacion_and_more'),
        ('prestamos', '0004_alter_prestamo_fechahorafinprestamo_and_more'),
        ('usuarios', '0002_razoncambio_usuario_lastlogin_historicalusuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalevento',
            fields=[
                ('idEvento', models.IntegerField(blank=True, db_index=True)),
                ('fechaHoraCreacion', models.DateTimeField()),
                ('nombreEvento', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=255)),
                ('fechaHoraEvento', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('flyer', models.BinaryField()),
                ('descripcion', models.TextField()),
                ('aforo', models.SmallIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoriaEvento_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='eventos.categoriaevento')),
                ('edificio_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prestamos.edificio')),
                ('history_change_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('numeroDocumento_AdministradorBienestar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical evento',
                'verbose_name_plural': 'historical eventos',
                'db_table': 'trazabilidadEventos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalevento_asistentes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='eventos.evento')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.historicalevento')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historicalevento_asistentes',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalevento_estadoEvento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoevento', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='eventos.estadoevento')),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='eventos.evento')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.historicalevento')),
            ],
            options={
                'verbose_name': 'Historicalevento_estadoEvento',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
