# Generated by Django 5.0.3 on 2024-06-02 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_tipoinforme_trazabilidadinformes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fechaHoraEventoFinal',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 7, 16, 520798)),
        ),
        migrations.AddField(
            model_name='historicalevento',
            name='fechaHoraEventoFinal',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 7, 16, 520798)),
        ),
    ]
