# Generated by Django 5.0.3 on 2024-03-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=45)),
                ('descripcionRol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('idTipoDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('siglasTipoDocumento', models.CharField(max_length=5)),
                ('descripcionTipoDocumento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('numeroDocumento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correoInstitucional', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('numeroCelular', models.CharField(max_length=15)),
                ('codigoVerificacion', models.IntegerField()),
                ('usuarioVerificado', models.BooleanField(default=False)),
                ('idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodocumento')),
                ('roles', models.ManyToManyField(to='usuarios.rol')),
            ],
        ),
    ]
