# Generated by Django 5.0.3 on 2024-05-13 17:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='razonCambio',
            fields=[
                ('idCambio', models.AutoField(primary_key=True, serialize=False)),
                ('razonCambio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Historicalusuario',
            fields=[
                ('numeroDocumento', models.IntegerField(db_index=True)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correoInstitucional', models.CharField(db_index=True, max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('numeroCelular', models.CharField(max_length=15)),
                ('codigoVerificacion', models.IntegerField()),
                ('usuarioVerificado', models.BooleanField(default=False)),
                ('lastLogin', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idTipoDocumento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.tipodocumento')),
                ('history_change_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio')),
            ],
            options={
                'verbose_name': 'historical usuario',
                'verbose_name_plural': 'historical usuarios',
                'db_table': 'trazabilidadUsuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalusuario_roles',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.historicalusuario')),
                ('rol', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.rol')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historicalusuario_roles',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
