# Generated by Django 5.0.3 on 2024-05-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_historicalusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='razonCambio',
            fields=[
                ('idCambio', models.AutoField(primary_key=True, serialize=False)),
                ('razonCambio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='history_change_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.razoncambio'),
        ),
    ]
