# Generated by Django 5.0.3 on 2024-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_razoncambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
    ]
