# Generated by Django 5.0.3 on 2024-05-11 21:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_historicalusuario_lastlogin_usuario_lastlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalusuario_roles',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.historicalusuario')),
                ('rol', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.rol')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historicalusuario_roles',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
