# Generated by Django 5.0.3 on 2024-05-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_historicalusuario_roles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalusuario',
            table='trazabilidadUsuarios',
        ),
    ]
